language: c

compiler:
    - gcc

before_install:
  - sudo apt-get -y install libncurses5-dev libncursesw5-dev

script:
    - cd assignments
    - gcc 2D_matrix_multiplication.c
    - gcc binarySearchTree.c
    - gcc depthFirstSearch.c
    - cd ../avl_vs_redblack
    - gcc avl_tree.c
    - gcc redblack_tree.c
