language: c

compiler:
    - gcc

script:
    - cd assignments
    - gcc 2D_matrix_multiplication.c
    - gcc binarySearchTree.c
    - gcc depthFirstSearch.c
    - cd ../avl_vs_redblack
    - gcc avl_tree.c
    - gcc redblack_tree.c
